# -*- coding: utf-8 -*-
"""TIN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SHrrh7F40WONnbu72Z8ATmeP3snf2hGB
"""

import cv2
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
#from google.colab.patches import cv2_imshow
class Point(object):
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def getX(self):
        return self.x
    def getY(self):
        return self.y
def gDiff(img,PointC,tmpPoint):
    return abs(int(img[PointC.x,PointC.y]) - int(img[tmpPoint.x,tmpPoint.y]))
def selectConnects(p):
    if p != 0:
        connects = [Point(-1, -1), Point(0, -1), Point(1, -1), Point(1, 0), Point(1, 1), \
                    Point(0, 1), Point(-1, 1), Point(-1, 0)]
    else:
        connects = [ Point(0, -1),  Point(1, 0),Point(0, 1), Point(-1, 0)]
    return connects


def regionGrow(img,seeds,thresh,p = 1):
    height, weight = img.shape
    seedMark = np.zeros(img.shape)
    seedList = []
    for seed in seeds:
        seedList.append(seed)
    label = 150
    connects = selectConnects(p)
    while(len(seedList)>0):
        PointC = seedList.pop(0)

        seedMark[PointC.x,PointC.y] = label
        for i in range(8):
            Xt = PointC.x + connects[i].x
            YT = PointC.y + connects[i].y
            if Xt < 0 or YT < 0 or Xt >= height or YT >= weight:
                continue
            Diff = gDiff(img,PointC,Point(Xt,YT))
            if Diff < thresh and seedMark[Xt,YT] == 0:
                seedMark[Xt,YT] = label
                seedList.append(Point(Xt,YT))
    #for i in range(len(seedMark)) :
     # for j in range(len(seedMark[i])) :
      #   print(i,j)          
       #  print(seedMark[i][j])
    return seedMark

img = np.array(Image.open("photo.jpg").convert("L"))
seeds = [Point(200,200),Point(200,480),Point(200,790),Point(200,1100),
         Point(500,170),Point(500,480),Point(500,790),Point(500,1081)]
#modifier

Img = regionGrow(img,seeds,thresh=10)
print(img.shape)
plt.imshow(Img, cmap='gray')
plt.show()

"""# Nouvelle section"""